#!/bin/bash

# QilbeeDB AI Agent Tests Setup Script
# Helps configure environment for running AI agent integration tests

set -e

echo "🤖 QilbeeDB AI Agent Tests Setup"
echo "================================"
echo ""

# Check if API key is already set
if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "✅ ANTHROPIC_API_KEY is already set"
    echo "   Value: ${ANTHROPIC_API_KEY:0:20}..."
    echo ""
    echo "To run tests:"
    echo "  cargo test --test ai_agent_integration_tests -- --nocapture"
    exit 0
fi

echo "⚠️  ANTHROPIC_API_KEY is not set"
echo ""
echo "You need an Anthropic API key to run these tests."
echo "Get one from: https://console.anthropic.com/settings/keys"
echo ""

# Ask user if they want to set it now
read -p "Do you have an API key? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    echo "Get your API key from: https://console.anthropic.com/settings/keys"
    echo "Then run this script again."
    exit 0
fi

# Get API key from user
echo ""
echo "Enter your Anthropic API key (starts with 'sk-ant-api03-'):"
read -r api_key

# Validate format
if [[ ! $api_key =~ ^sk-ant-api03- ]]; then
    echo "❌ Error: API key should start with 'sk-ant-api03-'"
    exit 1
fi

# Create .env file
echo "Creating .env file..."
cat > .env << EOF
# QilbeeDB Environment Variables
# Generated by setup-ai-tests.sh

# Anthropic API Key for AI Agent Integration Tests
ANTHROPIC_API_KEY=$api_key
EOF

echo "✅ .env file created"
echo ""

# Detect shell
shell_profile=""
if [ -n "$ZSH_VERSION" ]; then
    shell_profile="$HOME/.zshrc"
elif [ -n "$BASH_VERSION" ]; then
    shell_profile="$HOME/.bashrc"
else
    shell_profile="$HOME/.profile"
fi

# Ask if user wants to add to shell profile
echo "Would you like to add this to your shell profile ($shell_profile)?"
echo "This will make the key available in all terminal sessions."
read -p "(y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "" >> "$shell_profile"
    echo "# QilbeeDB Anthropic API Key" >> "$shell_profile"
    echo "export ANTHROPIC_API_KEY='$api_key'" >> "$shell_profile"
    echo "✅ Added to $shell_profile"
    echo ""
    echo "Run: source $shell_profile"
    echo "Or restart your terminal to load the key."
fi

# Export for current session
export ANTHROPIC_API_KEY="$api_key"

echo ""
echo "🎉 Setup complete!"
echo ""
echo "To run all AI agent tests:"
echo "  cargo test --test ai_agent_integration_tests -- --nocapture"
echo ""
echo "To run a specific test:"
echo "  cargo test --test ai_agent_integration_tests test_01_basic_agent_conversation_memory -- --nocapture"
echo ""
echo "For more information, see:"
echo "  tests/AI_AGENT_TESTS_README.md"
echo ""
